### ISSUE TITLE
Add Toast Notifications

### ISSUE THREAD

**Issue by sol3uk** [Odinnh/DECLASSIFIED#23]
Look for a good toast notification library and implement it for the most basic of notifications, i.e. "Link has been copied to your clipboard"

Possible candidates:
- https://www.jqueryscript.net/demo/Highly-Customizable-jQuery-Toast-Message-Plugin-Toastr/
- https://apvarun.github.io/toastify-js/#
- https://xrr2016.github.io/tata/

**Comment by iligalodin** [comment]
I am not too fond of either of them, what are the general messages we need to handle?

**Comment by sol3uk** [comment]
Yeah some are better than others, keep in mind they can be customized, or we could just make our own pop-up. 

The only messages we need to handle are just any errors and a message for the "share link being copied to the clipboard" for now.

**Comment by iligalodin** [comment]
For the copied i was thinking the google chrome approach a small fading popup with the message "copied" ill get a reference up soon.

I will be making my own popup in the style of cold war pretty soon! (expect one later today)

**Comment by Odinnh** [comment]
![image](https://user-images.githubusercontent.com/84709673/122920029-333f3180-d361-11eb-8fdc-eef54b9734a0.png)
i was thinking this for the copy prompt 



and this for any error message

![image](https://user-images.githubusercontent.com/84709673/122920063-40f4b700-d361-11eb-8b35-8b0eb99b9fe1.png)
