### ISSUE TITLE
Naviguation bar bug 

### ISSUE THREAD

**Issue by Spl4shh** [Odinnh/DECLASSIFIED#41]
I have seen that for example when you choose to look the Firebase's map, you only see the spawn area choice, the choice for the rest of the map is hidden under "map-display"

Idea of resolution :
Maybe just an priority problem

**Comment by Odinnh** [comment]
fixed with latest push

**Comment by Spl4shh** [comment]
What was the solution ? Just for my information

**Comment by iligalodin** [comment]
Overriding styles, these issues might pop up one in a while.
