### ISSUE TITLE
Aetherium Canister bug

### ISSUE THREAD

**Issue by Spl4shh** [Odinnh/DECLASSIFIED#42]
When you click on "Locate Intel" of  the Aetherium Canister, it just show you a black map on Alpine

**Comment by Spl4shh** [comment]
Same for different Item, 
Here is then list for the one I tried 

-GOLOVA - OFF THE HOOK
-AFTERMATH

**Comment by sol3uk** [comment]
Thanks for the submission @Spl4shh.
A pull request has been raised for this:
https://github.com/Odinnh/DECLASSIFIED/pull/44

**Comment by Spl4shh** [comment]
Maybe there are still some items who didn't work but I only wrote the one that I was searching at the moment
