### ISSUE TITLE
Peace is Our Profession Omega audio log

### ISSUE THREAD

**Issue by arekm** [Odinnh/DECLASSIFIED#43]
name of data(a.e. Maxis's Scarf)
Description ( this is optional for echoes or radios, etc)
Map (outbreak is for intel that can be found on all outbreak maps)
Location (these are coordinates, you can get them by pressing f12 type "debug = true" and clicking on the map. Now you have the coords in your clipboard)
Image of the correct location

* Peace is Our Profession - Omega audio log
* Underground bunker on the south, under the bed.
* Duga
* [-180.4048198209851, 130.7059783935547]
* https://preview.redd.it/dil0pirpx7b71.png?width=2560&format=png&auto=webp&s=a56323d1b2de4ccae2bd9610e92fc8506467c978
* https://preview.redd.it/5ha15irpx7b71.png?width=2560&format=png&auto=webp&s=5479c044c35a8d2b3f7eab786b416c1b92ff130a

**Comment by sol3uk** [comment]
@arekm thanks for the submission, we haven't updated our guide to ask for a season, but could I ask if this is season 5 intel?

**Comment by arekm** [comment]
Season 4 reloaded according to https://callofduty.fandom.com/wiki/Outbreak_(Cold_War)/Intel

btw. collateral map (even "empty") would be nice (no idea how these maps are made) to get new submissions

**Comment by sol3uk** [comment]
Thanks for the submission a pull request has been created here:
https://github.com/Odinnh/DECLASSIFIED/pull/46
