### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Spl4shh** [Odinnh/DECLASSIFIED#47]
When I click on the two maps of mauer der toten, I don't see the map

AND

There is no intel on collateral, is it right or is it a bug ?

**Comment by sol3uk** [comment]
Yeah still WIP, thanks for raising though. We should put something in to show they're not fully finished.

**Comment by Spl4shh** [comment]
Oh yeah for sure, I've just asked myself "why is it empty" XD

I've seen that the season 5 is missing so it logical that there is nothing 
Thx for the answer
