### ISSUE TITLE
New Intel: Ring of Fire Canister

### ISSUE THREAD

**Issue by bola2010** [Odinnh/DECLASSIFIED#53]
### Name

Ring of Fire Canister

### Faction

Requiem

### Season

Season 4

### Type of intel

Artifact

### Description

The artifact is in a yellow hanging coat inside the southernmost base cabin.

### Map

alpine

### Location Coordinates

[-103.51195549461748, 36.9375]

**Comment by sol3uk** [comment]
![image](https://user-images.githubusercontent.com/26093813/135429283-af1a95f6-dff9-430e-a030-c47ce2223ce7.png)
@bola2010 thanks for submitting. Please confirm this location is correct?
