### ISSUE TITLE
New Intel: Empty Elemental Pop

### ISSUE THREAD

**Issue by bola2010** [Odinnh/DECLASSIFIED#54]
### Name

Empty Elemental Pop

### Faction

Dark Aether

### Season

Season 4

### Type of intel

Artifact

### Description

The artifact can be found inside one of the small buildings at Lower West Town. The artifact is resting on a food shelf inside the kitchen area.

### Map

golova

### Location Coordinates

[-162.82115511107816, 165.8125]

**Comment by sol3uk** [comment]
![image](https://user-images.githubusercontent.com/26093813/135428771-b0023541-8ab4-4480-8c79-d47798d96d4b.png)
@bola2010 thanks for submitting. Please confirm this location is correct?

**Comment by bola2010** [comment]
Yup, collected it yesterday at shown location
