### ISSUE TITLE
New Intel: What Tomorrow Brings

### ISSUE THREAD

**Issue by bola2010** [Odinnh/DECLASSIFIED#55]
### Name

What Tomorrow Brings

### Faction

Requiem

### Season

Season 4

### Type of intel

Audio Log

### Description

The audio log is on a bar counter.

### Map

golova

### Location Coordinates

[-127.94974152785755, 138.625]

**Comment by sol3uk** [comment]
![image](https://user-images.githubusercontent.com/26093813/135425589-aba55df7-2c89-41d7-ae5a-51e94ca1cfe8.png)
@bola2010 thanks for submitting. Please confirm this location is correct?

**Comment by bola2010** [comment]
Yup, collected it yesterday at shown location
