### ISSUE TITLE
Additional information for intel + demented echo location

### ISSUE THREAD

**Issue by JugoSaiyajin** [Odinnh/DECLASSIFIED#6]
Intel: 
•Recon Rover Module
•more precise location (behind the sink in the bathroom, second floor)
•Outbreak, Zoo
![IntelZoo1](https://user-images.githubusercontent.com/86066679/122423998-a83fef00-cf8e-11eb-8401-65d35631fc20.PNG)

Second Intel I am not sure, I do not want to give false information but there was a radio where "Recon Rover Blues" is marked on the map. I found it here 
![IntelRuka1](https://user-images.githubusercontent.com/86066679/122424632-2ac8ae80-cf8f-11eb-895d-29be9abe178a.PNG)

Also seen on that image, to the right next to the table is a demented echo spawn.
(also idk if someone linked you this:
 https://www.reddit.com/r/CODZombies/comments/n79n6k/a_guide_to_find_the_recurring_things_in_outbreak/ 
but I think you can easily implement these in your interactive map.

Hope everything was clear

**Comment by Odinnh** [comment]
would you be able to provide propper co-ordinates? check #5  to see how

**Comment by Odinnh** [comment]
> easily implement these in your interactive map.

Thanks for the link, i will eventually mark all the demented echoes on the map!

**Comment by JugoSaiyajin** [comment]
> 
> 
> would you be able to provide propper co-ordinates? check #5 to see how

Yes I will do that once I go ingame, I screenshotted that before I knew about it. Might add other intel stuff if I find any!

**Comment by Odinnh** [comment]
Recon Rover Module  Updated In next Push
