### ISSUE TITLE
 Demented Echo

### ISSUE THREAD

**Issue by iligalodin** [Odinnh/DECLASSIFIED#7]
- Demented Echo

- On the second floor of the aquarium

- Zoo

![image](https://user-images.githubusercontent.com/86091855/122504623-a7c44a00-cfc8-11eb-9ba9-1c23274fe89e.png)

![image](https://user-images.githubusercontent.com/86091855/122504569-91b68980-cfc8-11eb-815b-3cf2fb12b311.png)

_Originally posted by @markisdabomb214 in https://github.com/Odinnh/DECLASSIFIED/issues/5#issuecomment-863738321_

**Comment by iligalodin** [comment]
> * Demented Echo
> * On the second floor of the aquarium
> * Zoo
> 


Thanks! Do you have accurate coordinates? You can get them like mentioned above?

**Comment by markisdabomb214** [comment]
> > * Demented Echo
> > * On the second floor of the aquarium
> > * Zoo
> 
> Thanks! Do you have accurate coordinates? You can get them like mentioned here; #5 ?

Finally figured it out, coords are [-154.4547581108373, 166.8768944269258]

**Comment by Odinnh** [comment]
added to the next push
