### ISSUE TITLE
Demented Echo (Zoo)

### ISSUE THREAD

**Issue by markisdabomb214** [Odinnh/DECLASSIFIED#8]
- Demented Echo
- In the stables near the aviary
- Zoo
- Coords: [-174.31503434714938, 148.222502654611]
![image](https://user-images.githubusercontent.com/86091855/122673090-e3b00880-d19c-11eb-9c3a-68e3cf4a88b4.png)
![image](https://user-images.githubusercontent.com/86091855/122673100-eb6fad00-d19c-11eb-9040-830e1503d1a0.png)

**Comment by Odinnh** [comment]
added to the next push
